stages:
  - test
  - gitleaks
  - trivy-fs
  - build-sonar
  - build-image

test-vote:
  stage: test
  image: python:3.12
  tags:
    - test_runner
  script:
    - cd vote
    - pip install -r requirements.txt
    - python -m compileall .

test-result:
  stage: test
  image: node:20
  tags:
    - test_runner
  script:
    - cd result
    - npm ci
    - node --check server.js

test-worker:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:7.0
  tags:
    - test_runner
  script:
    - cd worker
#   - curl -I --connect-timeout 10 https://api.nuget.org/v3/index.json #we can remove this line if we are sure that nuget.org is reachable from the runner
    - dotnet build

gitleaks:
  stage: gitleaks
  image: 
    name: zricethezav/gitleaks:latest
    entrypoint:
      - ""
  tags:
    - test_runner
  script:
    - gitleaks detect --source . --verbose --redact

trivy-fs:
  stage: trivy-fs
  image:
    name: aquasec/trivy:latest
    entrypoint:
      - ""
  tags:
    - test_runner
  script:
    - trivy fs --scanners vuln,secret,misconfig --exit-code 1 --severity HIGH,CRITICAL .

.build-sonar:
  stage: build-sonar
  image: 
    name: sonarsource/sonar-scanner-cli:11
    entrypoint: [""]
  tags:
    - test_runner
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
      - "${SONAR_USER_HOME}/cache"
  script: 
  - sonar-scanner -Dsonar.host.url="${SONAR_HOST_URL}"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_BRANCH == 'main'
    - if: $CI_COMMIT_BRANCH == 'develop'

build-result:
  stage: build-image
  image: docker:cli
  services:
    - name: docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  tags:
    - test_runner
  script:
    - docker build -t result:$CI_COMMIT_SHORT_SHA ./result

build-vote:
  stage: build-image
  image: docker:cli
  services:
    - name: docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  tags:
    - test_runner
  script:
    - docker build -t vote:$CI_COMMIT_SHORT_SHA ./vote

build-worker:
  stage: build-image
  image: docker:cli
  services:
    - name: docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  tags:
    - test_runner
  script:
    - docker build -t worker:$CI_COMMIT_SHORT_SHA ./worker